# Generated by Django 2.2.4 on 2021-11-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicaopagamento',
            name='Parcela',
        ),
        migrations.DeleteModel(
            name='Parcela',
        ),
    ]
