# Generated by Django 2.2.4 on 2021-11-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamentos', '0002_auto_20211106_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('CondicaoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CondicaoPagamento_Parcela', to='Pagamentos.CondicaoPagamento')),
                ('FormaPagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FormaPagamento_Parcela', to='Pagamentos.FormaPagamento')),
            ],
            options={
                'db_table': 'Parcela',
            },
        ),
    ]
