# Generated by Django 2.2.4 on 2021-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamentos', '0005_auto_20211106_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='Dias',
            field=models.IntegerField(default=0, verbose_name='Dias'),
        ),
    ]
