# Generated by Django 2.2.4 on 2021-11-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0005_auto_20210925_1443'),
        ('Pagamentos', '0006_parcela_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('ValorInicial', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Inicial')),
                ('ValorPago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Pago')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_ContaReceber', to='Pessoas.Cliente')),
                ('CondicaoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CondicaoPagamento_ContaReceber', to='Pagamentos.CondicaoPagamento')),
            ],
            options={
                'db_table': 'ContaReceber',
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('ValorInicial', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Inicial')),
                ('ValorPago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Pago')),
                ('CondicaoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CondicaoPagamento_ContaPagar', to='Pagamentos.CondicaoPagamento')),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Fornecedor_ContaPagar', to='Pessoas.Fornecedor')),
            ],
            options={
                'db_table': 'ContaPagar',
            },
        ),
    ]
