# Generated by Django 2.2.4 on 2021-11-15 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamentos', '0007_contapagar_contareceber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicaopagamento',
            name='DataRecebimento',
        ),
        migrations.RemoveField(
            model_name='condicaopagamento',
            name='DataVencimento',
        ),
        migrations.AddField(
            model_name='condicaopagamento',
            name='Desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condicaopagamento',
            name='Multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contapagar',
            name='DataVencimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='NumParcela',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contapagar',
            name='Pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='DataVencimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='NumParcela',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contareceber',
            name='Pago',
            field=models.BooleanField(default=False),
        ),
    ]
