# Generated by Django 2.2.4 on 2021-09-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoas', '0005_auto_20210925_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('CodigodeBarras', models.CharField(max_length=50, verbose_name='Código de Barras')),
                ('EstoqueAtual', models.IntegerField(verbose_name='Estoque Atual')),
                ('PrecoCusto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de Custo')),
                ('PrecoVenda', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de Venda')),
                ('Unidade', models.CharField(max_length=10)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Categoria_Produto', to='Produtos.Categoria')),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Fornecedor_Produto', to='Pessoas.Fornecedor')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Marca_Produto', to='Produtos.Marca')),
            ],
            options={
                'db_table': 'Produto',
            },
        ),
    ]
