# Generated by Django 2.2.4 on 2021-09-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cidade_Cliente', to='endereco.Cidade'),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RazaoSocial', models.CharField(max_length=100)),
                ('NomeFantasia', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=30)),
                ('Logradouro', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=20)),
                ('Numero', models.CharField(max_length=20)),
                ('Complemento', models.CharField(max_length=100)),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cidade_Fornecedor', to='endereco.Cidade')),
            ],
            options={
                'db_table': 'Fornecedor',
            },
        ),
    ]
