# Generated by Django 2.2.4 on 2021-09-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pessoas', '0002_auto_20210918_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargo',
            },
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cargo', to='Pessoas.Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
