# Generated by Django 2.2.4 on 2021-09-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0003_auto_20210918_0506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='Funcionario',
        ),
    ]
