# Generated by Django 2.2.4 on 2021-10-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
        ('Pessoas', '0005_auto_20210925_1443'),
        ('Gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroNota', models.CharField(max_length=50, verbose_name='Número da Nota')),
                ('SerieNota', models.CharField(max_length=50, verbose_name='Série da Nota')),
                ('ModeloNota', models.CharField(max_length=50, verbose_name='Modelo da Nota')),
                ('DataCompra', models.DateField(verbose_name='Data de Compra')),
                ('DataRecebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Compra_Fornecedor', to='Pessoas.Fornecedor')),
            ],
            options={
                'db_table': 'Compra',
            },
        ),
        migrations.AlterModelTable(
            name='itemvenda',
            table='ItemVenda',
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Total')),
                ('ValorUnitario', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Unitário')),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao.Compra')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produtos.Produto')),
            ],
            options={
                'db_table': 'ItemCompra',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='Produtos',
            field=models.ManyToManyField(through='Gestao.ItemCompra', to='Produtos.Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('NumeroNota', 'SerieNota', 'ModeloNota', 'Fornecedor')},
        ),
    ]
