# Generated by Django 2.2.4 on 2021-11-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamentos', '0007_contapagar_contareceber'),
        ('Gestao', '0002_auto_20211023_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='CondicaoPagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CondicaoPagamento_Compra', to='Pagamentos.CondicaoPagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='CondicaoPagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CondicaoPagamento_Venda', to='Pagamentos.CondicaoPagamento'),
            preserve_default=False,
        ),
    ]
