# Generated by Django 2.2.4 on 2021-09-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('sigla', models.CharField(max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('UF', models.CharField(max_length=3, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pais', to='endereco.Pais')),
            ],
            options={
                'db_table': 'Estado',
                'unique_together': {('pais', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado', to='endereco.Estado')),
            ],
            options={
                'db_table': 'Cidade',
                'unique_together': {('estado', 'nome')},
            },
        ),
    ]
