# Generated by Django 2.2.4 on 2021-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_auto_20190731_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='pais',
            name='ativo',
        ),
    ]
